on: release
jobs:
  pytest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '1'
      - run: uv sync
      - run: uv build
      - run: uv publish
